#!/usr/bin/env bash
# Script that installs Nginx server

# update package list
apt-get update -y

# install nginx
apt-get install nginx -y

# start nginx service
/etc/init.d/nginx start

# check if nginx is listening on port 80
netstat -tuln | grep :80

# check if nginx is returning 'Hello World!'
curl localhost
