#!/usr/bin/env bash
# Script that installs Nginx server

echo "Updating and installing Nginx"
sudo apt-get update -y -qq && \
    sudo apt-get install nginx -y

echo "Setting up some minor stuff."

# starting nginx service
sudo /etc/init.d/nginx start

# allowing nginx on firewall
sudo ufw allow 80/tcp

# Give the user ownership to website files for easy editing
sudo chown -R www-data:www-data /var/www/html
sudo chmod -R 755 /var/www/html

# Creating new index
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Restarting nginx
sudo /etc/init.d/nginx restart

echo "Completed."
