#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string

echo "Updating and installing Nginx"
sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y

echo "Setting up some minor stuff."

# starting nginx service
sudo /etc/init.d/nginx start

# allowing nginx on firewall
sudo ufw allow 80/tcp

# Give the user ownership to website files for easy editing
sudo chown -R www-data:www-data /var/www/html
sudo chmod -R 755 /var/www/html

# Creating new index
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting up redirect
echo "server {
    listen 80;
    server_name example.com;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/conf.d/redirect.conf > /dev/null

# Restarting nginx
sudo /etc/init.d/nginx restart

echo "Completed."
