#!/bin/bash
echo "Creating custom_headers.conf file"
sudo echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $hostname;
}
" > /etc/nginx/custom_headers.conf

echo "Including custom_headers.conf in nginx.conf"
sudo sed -i '/http {/a include /etc/nginx/custom_headers.conf;' /etc/nginx/nginx.conf

echo "Restarting Nginx"
sudo service nginx restart
